name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm install
        working-directory: ./packages/cin-crypto-js
      - run: npm audit signatures
        working-directory: ./packages/cin-crypto-js
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./packages/cin-crypto-js
